version: "3.8"

services:
  db:
    container_name: c_web_server_db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c_web_server
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # https://medium.com/@vinjenks/dockerized-local-postgres-and-scram-authentication-a-quick-fix-21c432951bd
